// Generated by gencpp from file path_follower/SteeringCurrent.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_STEERINGCURRENT_H
#define PATH_FOLLOWER_MESSAGE_STEERINGCURRENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_follower
{
template <class ContainerAllocator>
struct SteeringCurrent_
{
  typedef SteeringCurrent_<ContainerAllocator> Type;

  SteeringCurrent_()
    : steering_angle(0.0)  {
    }
  SteeringCurrent_(const ContainerAllocator& _alloc)
    : steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::path_follower::SteeringCurrent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::SteeringCurrent_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringCurrent_

typedef ::path_follower::SteeringCurrent_<std::allocator<void> > SteeringCurrent;

typedef boost::shared_ptr< ::path_follower::SteeringCurrent > SteeringCurrentPtr;
typedef boost::shared_ptr< ::path_follower::SteeringCurrent const> SteeringCurrentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::SteeringCurrent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::SteeringCurrent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_follower': ['/data/yang/code/aws/catkin_ws_docker/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::SteeringCurrent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::SteeringCurrent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::SteeringCurrent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::SteeringCurrent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::SteeringCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::SteeringCurrent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::SteeringCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a70504669a8dacda06aa18fb270817f";
  }

  static const char* value(const ::path_follower::SteeringCurrent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a70504669a8dacdULL;
  static const uint64_t static_value2 = 0xa06aa18fb270817fULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::SteeringCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/SteeringCurrent";
  }

  static const char* value(const ::path_follower::SteeringCurrent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::SteeringCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 steering_angle\n\
";
  }

  static const char* value(const ::path_follower::SteeringCurrent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::SteeringCurrent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringCurrent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::SteeringCurrent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::SteeringCurrent_<ContainerAllocator>& v)
  {
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_STEERINGCURRENT_H
