// Generated by gencpp from file path_follower/Trajectory2D.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_TRAJECTORY2D_H
#define PATH_FOLLOWER_MESSAGE_TRAJECTORY2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <path_follower/TrajectoryPoint2D.h>

namespace path_follower
{
template <class ContainerAllocator>
struct Trajectory2D_
{
  typedef Trajectory2D_<ContainerAllocator> Type;

  Trajectory2D_()
    : header()
    , point()  {
    }
  Trajectory2D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::path_follower::TrajectoryPoint2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::path_follower::TrajectoryPoint2D_<ContainerAllocator> >::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::path_follower::Trajectory2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::Trajectory2D_<ContainerAllocator> const> ConstPtr;

}; // struct Trajectory2D_

typedef ::path_follower::Trajectory2D_<std::allocator<void> > Trajectory2D;

typedef boost::shared_ptr< ::path_follower::Trajectory2D > Trajectory2DPtr;
typedef boost::shared_ptr< ::path_follower::Trajectory2D const> Trajectory2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::Trajectory2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::Trajectory2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_follower': ['/data/yang/code/aws/catkin_ws_docker/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Trajectory2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Trajectory2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Trajectory2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Trajectory2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Trajectory2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Trajectory2D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a195a064b3031199d911bad5e3e3d69";
  }

  static const char* value(const ::path_follower::Trajectory2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a195a064b303119ULL;
  static const uint64_t static_value2 = 0x9d911bad5e3e3d69ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/Trajectory2D";
  }

  static const char* value(const ::path_follower::Trajectory2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
TrajectoryPoint2D[] point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: path_follower/TrajectoryPoint2D\n\
#Header header  not sent directly\n\
float64 t\n\
float64 x\n\
float64 y\n\
float64 theta\n\
float64 kappa\n\
float64 kappa_dot\n\
float64 v\n\
float64 a\n\
float64 jerk\n\
float64 delta_theta     # heading misalignment with center line\n\
float64 d               # offset to center line\n\
float64 a_lat           # lateral (to traj not to center line!) acceleration\n\
";
  }

  static const char* value(const ::path_follower::Trajectory2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::Trajectory2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trajectory2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::Trajectory2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::Trajectory2D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_follower::TrajectoryPoint2D_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_TRAJECTORY2D_H
