// Generated by gencpp from file path_follower/Uout.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_UOUT_H
#define PATH_FOLLOWER_MESSAGE_UOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_follower
{
template <class ContainerAllocator>
struct Uout_
{
  typedef Uout_<ContainerAllocator> Type;

  Uout_()
    : acceleration(0.0)
    , del(0.0)  {
    }
  Uout_(const ContainerAllocator& _alloc)
    : acceleration(0.0)
    , del(0.0)  {
  (void)_alloc;
    }



   typedef double _acceleration_type;
  _acceleration_type acceleration;

   typedef double _del_type;
  _del_type del;





  typedef boost::shared_ptr< ::path_follower::Uout_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::Uout_<ContainerAllocator> const> ConstPtr;

}; // struct Uout_

typedef ::path_follower::Uout_<std::allocator<void> > Uout;

typedef boost::shared_ptr< ::path_follower::Uout > UoutPtr;
typedef boost::shared_ptr< ::path_follower::Uout const> UoutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::Uout_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::Uout_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_follower': ['/data/yang/code/aws/catkin_ws_docker/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Uout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Uout_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Uout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Uout_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Uout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Uout_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::Uout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73950a8bce4b9e8951518131a3cbe7f8";
  }

  static const char* value(const ::path_follower::Uout_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73950a8bce4b9e89ULL;
  static const uint64_t static_value2 = 0x51518131a3cbe7f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::Uout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/Uout";
  }

  static const char* value(const ::path_follower::Uout_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::Uout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acceleration\n\
float64 del\n\
";
  }

  static const char* value(const ::path_follower::Uout_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::Uout_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration);
      stream.next(m.del);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Uout_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::Uout_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::Uout_<ContainerAllocator>& v)
  {
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
    s << indent << "del: ";
    Printer<double>::stream(s, indent + "  ", v.del);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_UOUT_H
