// Generated by gencpp from file path_follower/Waypoints.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_WAYPOINTS_H
#define PATH_FOLLOWER_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_follower/Point2D.h>

namespace path_follower
{
template <class ContainerAllocator>
struct Waypoints_
{
  typedef Waypoints_<ContainerAllocator> Type;

  Waypoints_()
    : points()
    , dt(0.0)  {
    }
  Waypoints_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , dt(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::path_follower::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::path_follower::Point2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef float _dt_type;
  _dt_type dt;





  typedef boost::shared_ptr< ::path_follower::Waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::Waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoints_

typedef ::path_follower::Waypoints_<std::allocator<void> > Waypoints;

typedef boost::shared_ptr< ::path_follower::Waypoints > WaypointsPtr;
typedef boost::shared_ptr< ::path_follower::Waypoints const> WaypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::Waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::Waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_follower': ['/data/yang/code/aws/catkin_ws_docker/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfb75f45f26568fb46a75f56fa6b81e2";
  }

  static const char* value(const ::path_follower::Waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfb75f45f26568fbULL;
  static const uint64_t static_value2 = 0x46a75f56fa6b81e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/Waypoints";
  }

  static const char* value(const ::path_follower::Waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2D[] points\n\
float32 dt\n\
\n\
================================================================================\n\
MSG: path_follower/Point2D\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::path_follower::Waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::Waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.dt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::Waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::Waypoints_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_follower::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "dt: ";
    Printer<float>::stream(s, indent + "  ", v.dt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_WAYPOINTS_H
