(cl:defpackage path_follower-msg
  (:use )
  (:export
   "<ACTUATOR>"
   "ACTUATOR"
   "<APPLANIXPOSE>"
   "APPLANIXPOSE"
   "<CONTROLLERTARGET>"
   "CONTROLLERTARGET"
   "<POINT2D>"
   "POINT2D"
   "<STEERINGCMD>"
   "STEERINGCMD"
   "<STEERINGCURRENT>"
   "STEERINGCURRENT"
   "<TIME>"
   "TIME"
   "<TRAJECTORY2D>"
   "TRAJECTORY2D"
   "<TRAJECTORYPOINT2D>"
   "TRAJECTORYPOINT2D"
   "<UOUT>"
   "UOUT"
   "<WAYPOINTS>"
   "WAYPOINTS"
   "<STATE_DYNAMIC>"
   "STATE_DYNAMIC"
  ))

