language: python
python:
  - "3.5"
install:
  - pip install pycodestyle cpplint
script:
    # List the remaining errors - these will have to be fixed manually
    - pycodestyle --show-source --exclude gamewrap,gameclient .
    - cpplint --extensions=hpp,cpp --recursive hybrid_client
